exclude: [Gemfile, Gemfile.lock, README.txt, README.md, LICENSE.txt, run_local.sh, CNAME]

prologue:
        author: Torita and Mark
        byline: April 7th, 2018
        avatar: images/avatar.png
        copyright: "2018 Torita &amp; Mark Igariwey. All rights reserved."
        bottom: 
                - "Design by <a href=\"https://twitter.com/ms_dacres\">Shana Dacres</a>"
                - "Photos by ???"
        social:
                # Icons can be found here: http://fontawesome.io/icons/
                # (you don't need the "fa-" prefix)
              - text: Twitter
                href: "#"
                icon: twitter

